// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/notes/item": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Новая заметка"
                ],
                "summary": "Создать новую заметку",
                "parameters": [
                    {
                        "description": "Note data",
                        "name": "newNote",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/repository.NewNote"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The note has been successfully created",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid request: the note hasn't been created",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/notes/item/id": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Заметка по ID"
                ],
                "summary": "Получить заметку по ее идентификатору",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Note ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Getting the note is successful",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not found: such a note doesn't exist",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Изменить заметку"
                ],
                "summary": "Изменить заметку по ее ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Note ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Note data",
                        "name": "updatedNote",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/repository.ChangingNote"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The note has been successfully updated",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid request: the note hasn't been updated",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Удалить заметку"
                ],
                "summary": "Удалить заметку по ее ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Note ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The note has been successfully deleted",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid request: the note hasn't been deleted",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not found: such a note doesn't exist",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/notes/items": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Заметки"
                ],
                "summary": "Получить все заметки",
                "responses": {
                    "200": {
                        "description": "Getting notes is successful",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/tasks/item": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Новая задача"
                ],
                "summary": "Создать новую задачу",
                "parameters": [
                    {
                        "description": "Task data",
                        "name": "newTask",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/repository.NewTask"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The task has been successfully created",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid request: the task hasn't been created",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/tasks/item/id": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Задача по ID"
                ],
                "summary": "Получить задачу по ее идентификатору",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Task ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Getting the task is successful",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not found: such a task doesn't exist",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Изменить задачу"
                ],
                "summary": "Изменить задачу по ее ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Task ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Task data",
                        "name": "updatedTask",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/repository.ChangingTask"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The task has been successfully updated",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid request: the task hasn't been updated",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Удалить задачу"
                ],
                "summary": "Удалить задачу по ее ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Task ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The task has been successfully deleted",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid request: the task hasn't been deleted",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not found: such a task doesn't exist",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/tasks/items": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Задачи"
                ],
                "summary": "Получить все задачи",
                "responses": {
                    "200": {
                        "description": "Getting tasks is successful",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "repository.ChangingNote": {
            "type": "object",
            "properties": {
                "alarmTimeStamp": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "repository.ChangingTask": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "dueDate": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "repository.NewNote": {
            "type": "object",
            "required": [
                "alarmTime",
                "description",
                "name"
            ],
            "properties": {
                "alarmTime": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "repository.NewTask": {
            "type": "object",
            "required": [
                "description",
                "dueDate",
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "dueDate": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1",
	Host:             "localhost:8080/",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Программа для управления задачами",
	Description:      "API Server",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
