// protoc -I. -I path_to_probuf\include --go_out=. --go-grpc_out=. api/grpc/v1/remindables.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: api/grpc/v1/remindables.proto

package remindables_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RemindablesService_GetTasks_FullMethodName       = "/remindables.v1.RemindablesService/GetTasks"
	RemindablesService_GetNotes_FullMethodName       = "/remindables.v1.RemindablesService/GetNotes"
	RemindablesService_GetTasksById_FullMethodName   = "/remindables.v1.RemindablesService/GetTasksById"
	RemindablesService_GetNotesById_FullMethodName   = "/remindables.v1.RemindablesService/GetNotesById"
	RemindablesService_PostNewTask_FullMethodName    = "/remindables.v1.RemindablesService/PostNewTask"
	RemindablesService_PostNewNote_FullMethodName    = "/remindables.v1.RemindablesService/PostNewNote"
	RemindablesService_PutTaskById_FullMethodName    = "/remindables.v1.RemindablesService/PutTaskById"
	RemindablesService_PutNoteById_FullMethodName    = "/remindables.v1.RemindablesService/PutNoteById"
	RemindablesService_DeleteTaskById_FullMethodName = "/remindables.v1.RemindablesService/DeleteTaskById"
	RemindablesService_DeleteNoteById_FullMethodName = "/remindables.v1.RemindablesService/DeleteNoteById"
)

// RemindablesServiceClient is the client API for RemindablesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RemindablesServiceClient interface {
	GetTasks(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetTaskResponse], error)
	GetNotes(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetNoteResponse], error)
	GetTasksById(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*GetTaskResponse, error)
	GetNotesById(ctx context.Context, in *GetNoteRequest, opts ...grpc.CallOption) (*GetNoteResponse, error)
	PostNewTask(ctx context.Context, in *PostNewTaskRequest, opts ...grpc.CallOption) (*PostNewTaskResponse, error)
	PostNewNote(ctx context.Context, in *PostNewNoteRequest, opts ...grpc.CallOption) (*PostNewNoteResponse, error)
	PutTaskById(ctx context.Context, in *PutTaskRequest, opts ...grpc.CallOption) (*PutTaskResponse, error)
	PutNoteById(ctx context.Context, in *PutNoteRequest, opts ...grpc.CallOption) (*PutNoteResponse, error)
	DeleteTaskById(ctx context.Context, in *DeleteTaskRequest, opts ...grpc.CallOption) (*DeleteTaskResponse, error)
	DeleteNoteById(ctx context.Context, in *DeleteNoteRequest, opts ...grpc.CallOption) (*DeleteNoteResponse, error)
}

type remindablesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRemindablesServiceClient(cc grpc.ClientConnInterface) RemindablesServiceClient {
	return &remindablesServiceClient{cc}
}

func (c *remindablesServiceClient) GetTasks(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetTaskResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RemindablesService_ServiceDesc.Streams[0], RemindablesService_GetTasks_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, GetTaskResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RemindablesService_GetTasksClient = grpc.ServerStreamingClient[GetTaskResponse]

func (c *remindablesServiceClient) GetNotes(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetNoteResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RemindablesService_ServiceDesc.Streams[1], RemindablesService_GetNotes_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, GetNoteResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RemindablesService_GetNotesClient = grpc.ServerStreamingClient[GetNoteResponse]

func (c *remindablesServiceClient) GetTasksById(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*GetTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskResponse)
	err := c.cc.Invoke(ctx, RemindablesService_GetTasksById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remindablesServiceClient) GetNotesById(ctx context.Context, in *GetNoteRequest, opts ...grpc.CallOption) (*GetNoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNoteResponse)
	err := c.cc.Invoke(ctx, RemindablesService_GetNotesById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remindablesServiceClient) PostNewTask(ctx context.Context, in *PostNewTaskRequest, opts ...grpc.CallOption) (*PostNewTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostNewTaskResponse)
	err := c.cc.Invoke(ctx, RemindablesService_PostNewTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remindablesServiceClient) PostNewNote(ctx context.Context, in *PostNewNoteRequest, opts ...grpc.CallOption) (*PostNewNoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostNewNoteResponse)
	err := c.cc.Invoke(ctx, RemindablesService_PostNewNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remindablesServiceClient) PutTaskById(ctx context.Context, in *PutTaskRequest, opts ...grpc.CallOption) (*PutTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutTaskResponse)
	err := c.cc.Invoke(ctx, RemindablesService_PutTaskById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remindablesServiceClient) PutNoteById(ctx context.Context, in *PutNoteRequest, opts ...grpc.CallOption) (*PutNoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutNoteResponse)
	err := c.cc.Invoke(ctx, RemindablesService_PutNoteById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remindablesServiceClient) DeleteTaskById(ctx context.Context, in *DeleteTaskRequest, opts ...grpc.CallOption) (*DeleteTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTaskResponse)
	err := c.cc.Invoke(ctx, RemindablesService_DeleteTaskById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remindablesServiceClient) DeleteNoteById(ctx context.Context, in *DeleteNoteRequest, opts ...grpc.CallOption) (*DeleteNoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteNoteResponse)
	err := c.cc.Invoke(ctx, RemindablesService_DeleteNoteById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RemindablesServiceServer is the server API for RemindablesService service.
// All implementations must embed UnimplementedRemindablesServiceServer
// for forward compatibility.
type RemindablesServiceServer interface {
	GetTasks(*emptypb.Empty, grpc.ServerStreamingServer[GetTaskResponse]) error
	GetNotes(*emptypb.Empty, grpc.ServerStreamingServer[GetNoteResponse]) error
	GetTasksById(context.Context, *GetTaskRequest) (*GetTaskResponse, error)
	GetNotesById(context.Context, *GetNoteRequest) (*GetNoteResponse, error)
	PostNewTask(context.Context, *PostNewTaskRequest) (*PostNewTaskResponse, error)
	PostNewNote(context.Context, *PostNewNoteRequest) (*PostNewNoteResponse, error)
	PutTaskById(context.Context, *PutTaskRequest) (*PutTaskResponse, error)
	PutNoteById(context.Context, *PutNoteRequest) (*PutNoteResponse, error)
	DeleteTaskById(context.Context, *DeleteTaskRequest) (*DeleteTaskResponse, error)
	DeleteNoteById(context.Context, *DeleteNoteRequest) (*DeleteNoteResponse, error)
	mustEmbedUnimplementedRemindablesServiceServer()
}

// UnimplementedRemindablesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRemindablesServiceServer struct{}

func (UnimplementedRemindablesServiceServer) GetTasks(*emptypb.Empty, grpc.ServerStreamingServer[GetTaskResponse]) error {
	return status.Error(codes.Unimplemented, "method GetTasks not implemented")
}
func (UnimplementedRemindablesServiceServer) GetNotes(*emptypb.Empty, grpc.ServerStreamingServer[GetNoteResponse]) error {
	return status.Error(codes.Unimplemented, "method GetNotes not implemented")
}
func (UnimplementedRemindablesServiceServer) GetTasksById(context.Context, *GetTaskRequest) (*GetTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTasksById not implemented")
}
func (UnimplementedRemindablesServiceServer) GetNotesById(context.Context, *GetNoteRequest) (*GetNoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNotesById not implemented")
}
func (UnimplementedRemindablesServiceServer) PostNewTask(context.Context, *PostNewTaskRequest) (*PostNewTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PostNewTask not implemented")
}
func (UnimplementedRemindablesServiceServer) PostNewNote(context.Context, *PostNewNoteRequest) (*PostNewNoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PostNewNote not implemented")
}
func (UnimplementedRemindablesServiceServer) PutTaskById(context.Context, *PutTaskRequest) (*PutTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutTaskById not implemented")
}
func (UnimplementedRemindablesServiceServer) PutNoteById(context.Context, *PutNoteRequest) (*PutNoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutNoteById not implemented")
}
func (UnimplementedRemindablesServiceServer) DeleteTaskById(context.Context, *DeleteTaskRequest) (*DeleteTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTaskById not implemented")
}
func (UnimplementedRemindablesServiceServer) DeleteNoteById(context.Context, *DeleteNoteRequest) (*DeleteNoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteNoteById not implemented")
}
func (UnimplementedRemindablesServiceServer) mustEmbedUnimplementedRemindablesServiceServer() {}
func (UnimplementedRemindablesServiceServer) testEmbeddedByValue()                            {}

// UnsafeRemindablesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RemindablesServiceServer will
// result in compilation errors.
type UnsafeRemindablesServiceServer interface {
	mustEmbedUnimplementedRemindablesServiceServer()
}

func RegisterRemindablesServiceServer(s grpc.ServiceRegistrar, srv RemindablesServiceServer) {
	// If the following call panics, it indicates UnimplementedRemindablesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RemindablesService_ServiceDesc, srv)
}

func _RemindablesService_GetTasks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RemindablesServiceServer).GetTasks(m, &grpc.GenericServerStream[emptypb.Empty, GetTaskResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RemindablesService_GetTasksServer = grpc.ServerStreamingServer[GetTaskResponse]

func _RemindablesService_GetNotes_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RemindablesServiceServer).GetNotes(m, &grpc.GenericServerStream[emptypb.Empty, GetNoteResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RemindablesService_GetNotesServer = grpc.ServerStreamingServer[GetNoteResponse]

func _RemindablesService_GetTasksById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemindablesServiceServer).GetTasksById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemindablesService_GetTasksById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemindablesServiceServer).GetTasksById(ctx, req.(*GetTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemindablesService_GetNotesById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemindablesServiceServer).GetNotesById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemindablesService_GetNotesById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemindablesServiceServer).GetNotesById(ctx, req.(*GetNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemindablesService_PostNewTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostNewTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemindablesServiceServer).PostNewTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemindablesService_PostNewTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemindablesServiceServer).PostNewTask(ctx, req.(*PostNewTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemindablesService_PostNewNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostNewNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemindablesServiceServer).PostNewNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemindablesService_PostNewNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemindablesServiceServer).PostNewNote(ctx, req.(*PostNewNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemindablesService_PutTaskById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemindablesServiceServer).PutTaskById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemindablesService_PutTaskById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemindablesServiceServer).PutTaskById(ctx, req.(*PutTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemindablesService_PutNoteById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemindablesServiceServer).PutNoteById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemindablesService_PutNoteById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemindablesServiceServer).PutNoteById(ctx, req.(*PutNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemindablesService_DeleteTaskById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemindablesServiceServer).DeleteTaskById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemindablesService_DeleteTaskById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemindablesServiceServer).DeleteTaskById(ctx, req.(*DeleteTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemindablesService_DeleteNoteById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemindablesServiceServer).DeleteNoteById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemindablesService_DeleteNoteById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemindablesServiceServer).DeleteNoteById(ctx, req.(*DeleteNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RemindablesService_ServiceDesc is the grpc.ServiceDesc for RemindablesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RemindablesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "remindables.v1.RemindablesService",
	HandlerType: (*RemindablesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTasksById",
			Handler:    _RemindablesService_GetTasksById_Handler,
		},
		{
			MethodName: "GetNotesById",
			Handler:    _RemindablesService_GetNotesById_Handler,
		},
		{
			MethodName: "PostNewTask",
			Handler:    _RemindablesService_PostNewTask_Handler,
		},
		{
			MethodName: "PostNewNote",
			Handler:    _RemindablesService_PostNewNote_Handler,
		},
		{
			MethodName: "PutTaskById",
			Handler:    _RemindablesService_PutTaskById_Handler,
		},
		{
			MethodName: "PutNoteById",
			Handler:    _RemindablesService_PutNoteById_Handler,
		},
		{
			MethodName: "DeleteTaskById",
			Handler:    _RemindablesService_DeleteTaskById_Handler,
		},
		{
			MethodName: "DeleteNoteById",
			Handler:    _RemindablesService_DeleteNoteById_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetTasks",
			Handler:       _RemindablesService_GetTasks_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetNotes",
			Handler:       _RemindablesService_GetNotes_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/grpc/v1/remindables.proto",
}
