// protoc -I. -I path_to_probuf\include --go_out=. --go-grpc_out=. api/grpc/v1/remindables.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/grpc/v1/remindables.proto

package remindables_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_api_grpc_v1_remindables_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_remindables_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_remindables_proto_rawDescGZIP(), []int{0}
}

func (x *GetTaskRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNoteRequest) Reset() {
	*x = GetNoteRequest{}
	mi := &file_api_grpc_v1_remindables_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNoteRequest) ProtoMessage() {}

func (x *GetNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_remindables_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNoteRequest.ProtoReflect.Descriptor instead.
func (*GetNoteRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_remindables_proto_rawDescGZIP(), []int{1}
}

func (x *GetNoteRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PostNewTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	DueDate       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=dueDate,proto3" json:"dueDate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostNewTaskRequest) Reset() {
	*x = PostNewTaskRequest{}
	mi := &file_api_grpc_v1_remindables_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostNewTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostNewTaskRequest) ProtoMessage() {}

func (x *PostNewTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_remindables_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostNewTaskRequest.ProtoReflect.Descriptor instead.
func (*PostNewTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_remindables_proto_rawDescGZIP(), []int{2}
}

func (x *PostNewTaskRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PostNewTaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PostNewTaskRequest) GetDueDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DueDate
	}
	return nil
}

type PostNewNoteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	AlarmTimeStamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=alarmTimeStamp,proto3" json:"alarmTimeStamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PostNewNoteRequest) Reset() {
	*x = PostNewNoteRequest{}
	mi := &file_api_grpc_v1_remindables_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostNewNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostNewNoteRequest) ProtoMessage() {}

func (x *PostNewNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_remindables_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostNewNoteRequest.ProtoReflect.Descriptor instead.
func (*PostNewNoteRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_remindables_proto_rawDescGZIP(), []int{3}
}

func (x *PostNewNoteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PostNewNoteRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PostNewNoteRequest) GetAlarmTimeStamp() *timestamppb.Timestamp {
	if x != nil {
		return x.AlarmTimeStamp
	}
	return nil
}

type PutTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	DueDate       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=dueDate,proto3" json:"dueDate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutTaskRequest) Reset() {
	*x = PutTaskRequest{}
	mi := &file_api_grpc_v1_remindables_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutTaskRequest) ProtoMessage() {}

func (x *PutTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_remindables_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutTaskRequest.ProtoReflect.Descriptor instead.
func (*PutTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_remindables_proto_rawDescGZIP(), []int{4}
}

func (x *PutTaskRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PutTaskRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PutTaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PutTaskRequest) GetDueDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DueDate
	}
	return nil
}

type PutNoteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	AlarmTimeStamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=alarmTimeStamp,proto3" json:"alarmTimeStamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PutNoteRequest) Reset() {
	*x = PutNoteRequest{}
	mi := &file_api_grpc_v1_remindables_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutNoteRequest) ProtoMessage() {}

func (x *PutNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_remindables_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutNoteRequest.ProtoReflect.Descriptor instead.
func (*PutNoteRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_remindables_proto_rawDescGZIP(), []int{5}
}

func (x *PutNoteRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PutNoteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PutNoteRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PutNoteRequest) GetAlarmTimeStamp() *timestamppb.Timestamp {
	if x != nil {
		return x.AlarmTimeStamp
	}
	return nil
}

type DeleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskRequest) Reset() {
	*x = DeleteTaskRequest{}
	mi := &file_api_grpc_v1_remindables_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskRequest) ProtoMessage() {}

func (x *DeleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_remindables_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_remindables_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteTaskRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNoteRequest) Reset() {
	*x = DeleteNoteRequest{}
	mi := &file_api_grpc_v1_remindables_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNoteRequest) ProtoMessage() {}

func (x *DeleteNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_remindables_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNoteRequest.ProtoReflect.Descriptor instead.
func (*DeleteNoteRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_remindables_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteNoteRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	InitTimeStamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=initTimeStamp,proto3" json:"initTimeStamp,omitempty"`
	DueDate       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=dueDate,proto3" json:"dueDate,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_api_grpc_v1_remindables_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_remindables_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_remindables_proto_rawDescGZIP(), []int{8}
}

func (x *GetTaskResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetTaskResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetTaskResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetTaskResponse) GetInitTimeStamp() *timestamppb.Timestamp {
	if x != nil {
		return x.InitTimeStamp
	}
	return nil
}

func (x *GetTaskResponse) GetDueDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DueDate
	}
	return nil
}

func (x *GetTaskResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetNoteResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	AlarmTimeStamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=alarmTimeStamp,proto3" json:"alarmTimeStamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetNoteResponse) Reset() {
	*x = GetNoteResponse{}
	mi := &file_api_grpc_v1_remindables_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNoteResponse) ProtoMessage() {}

func (x *GetNoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_remindables_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNoteResponse.ProtoReflect.Descriptor instead.
func (*GetNoteResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_remindables_proto_rawDescGZIP(), []int{9}
}

func (x *GetNoteResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetNoteResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetNoteResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetNoteResponse) GetAlarmTimeStamp() *timestamppb.Timestamp {
	if x != nil {
		return x.AlarmTimeStamp
	}
	return nil
}

type PostNewTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	InitTimeStamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=initTimeStamp,proto3" json:"initTimeStamp,omitempty"`
	DueDate       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=dueDate,proto3" json:"dueDate,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostNewTaskResponse) Reset() {
	*x = PostNewTaskResponse{}
	mi := &file_api_grpc_v1_remindables_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostNewTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostNewTaskResponse) ProtoMessage() {}

func (x *PostNewTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_remindables_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostNewTaskResponse.ProtoReflect.Descriptor instead.
func (*PostNewTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_remindables_proto_rawDescGZIP(), []int{10}
}

func (x *PostNewTaskResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PostNewTaskResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PostNewTaskResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PostNewTaskResponse) GetInitTimeStamp() *timestamppb.Timestamp {
	if x != nil {
		return x.InitTimeStamp
	}
	return nil
}

func (x *PostNewTaskResponse) GetDueDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DueDate
	}
	return nil
}

func (x *PostNewTaskResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type PostNewNoteResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	AlarmTimeStamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=alarmTimeStamp,proto3" json:"alarmTimeStamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PostNewNoteResponse) Reset() {
	*x = PostNewNoteResponse{}
	mi := &file_api_grpc_v1_remindables_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostNewNoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostNewNoteResponse) ProtoMessage() {}

func (x *PostNewNoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_remindables_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostNewNoteResponse.ProtoReflect.Descriptor instead.
func (*PostNewNoteResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_remindables_proto_rawDescGZIP(), []int{11}
}

func (x *PostNewNoteResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PostNewNoteResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PostNewNoteResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PostNewNoteResponse) GetAlarmTimeStamp() *timestamppb.Timestamp {
	if x != nil {
		return x.AlarmTimeStamp
	}
	return nil
}

type PutTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	InitTimeStamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=initTimeStamp,proto3" json:"initTimeStamp,omitempty"`
	DueDate       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=dueDate,proto3" json:"dueDate,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutTaskResponse) Reset() {
	*x = PutTaskResponse{}
	mi := &file_api_grpc_v1_remindables_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutTaskResponse) ProtoMessage() {}

func (x *PutTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_remindables_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutTaskResponse.ProtoReflect.Descriptor instead.
func (*PutTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_remindables_proto_rawDescGZIP(), []int{12}
}

func (x *PutTaskResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PutTaskResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PutTaskResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PutTaskResponse) GetInitTimeStamp() *timestamppb.Timestamp {
	if x != nil {
		return x.InitTimeStamp
	}
	return nil
}

func (x *PutTaskResponse) GetDueDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DueDate
	}
	return nil
}

func (x *PutTaskResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type PutNoteResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	AlarmTimeStamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=alarmTimeStamp,proto3" json:"alarmTimeStamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PutNoteResponse) Reset() {
	*x = PutNoteResponse{}
	mi := &file_api_grpc_v1_remindables_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutNoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutNoteResponse) ProtoMessage() {}

func (x *PutNoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_remindables_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutNoteResponse.ProtoReflect.Descriptor instead.
func (*PutNoteResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_remindables_proto_rawDescGZIP(), []int{13}
}

func (x *PutNoteResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PutNoteResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PutNoteResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PutNoteResponse) GetAlarmTimeStamp() *timestamppb.Timestamp {
	if x != nil {
		return x.AlarmTimeStamp
	}
	return nil
}

type DeleteTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	InitTimeStamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=initTimeStamp,proto3" json:"initTimeStamp,omitempty"`
	DueDate       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=dueDate,proto3" json:"dueDate,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskResponse) Reset() {
	*x = DeleteTaskResponse{}
	mi := &file_api_grpc_v1_remindables_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskResponse) ProtoMessage() {}

func (x *DeleteTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_remindables_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskResponse.ProtoReflect.Descriptor instead.
func (*DeleteTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_remindables_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteTaskResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteTaskResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteTaskResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DeleteTaskResponse) GetInitTimeStamp() *timestamppb.Timestamp {
	if x != nil {
		return x.InitTimeStamp
	}
	return nil
}

func (x *DeleteTaskResponse) GetDueDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DueDate
	}
	return nil
}

func (x *DeleteTaskResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DeleteNoteResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	AlarmTimeStamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=alarmTimeStamp,proto3" json:"alarmTimeStamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteNoteResponse) Reset() {
	*x = DeleteNoteResponse{}
	mi := &file_api_grpc_v1_remindables_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNoteResponse) ProtoMessage() {}

func (x *DeleteNoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_remindables_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNoteResponse.ProtoReflect.Descriptor instead.
func (*DeleteNoteResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_remindables_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteNoteResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteNoteResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteNoteResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DeleteNoteResponse) GetAlarmTimeStamp() *timestamppb.Timestamp {
	if x != nil {
		return x.AlarmTimeStamp
	}
	return nil
}

var File_api_grpc_v1_remindables_proto protoreflect.FileDescriptor

const file_api_grpc_v1_remindables_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/grpc/v1/remindables.proto\x12\x0eremindables.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\" \n" +
	"\x0eGetTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\" \n" +
	"\x0eGetNoteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x80\x01\n" +
	"\x12PostNewTaskRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x124\n" +
	"\adueDate\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\adueDate\"\x8e\x01\n" +
	"\x12PostNewNoteRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12B\n" +
	"\x0ealarmTimeStamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0ealarmTimeStamp\"\x8c\x01\n" +
	"\x0ePutTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x124\n" +
	"\adueDate\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\adueDate\"\x9a\x01\n" +
	"\x0ePutNoteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12B\n" +
	"\x0ealarmTimeStamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0ealarmTimeStamp\"#\n" +
	"\x11DeleteTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"#\n" +
	"\x11DeleteNoteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\xe7\x01\n" +
	"\x0fGetTaskResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12@\n" +
	"\rinitTimeStamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rinitTimeStamp\x124\n" +
	"\adueDate\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\adueDate\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"\x9b\x01\n" +
	"\x0fGetNoteResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12B\n" +
	"\x0ealarmTimeStamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0ealarmTimeStamp\"\xeb\x01\n" +
	"\x13PostNewTaskResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12@\n" +
	"\rinitTimeStamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rinitTimeStamp\x124\n" +
	"\adueDate\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\adueDate\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"\x9f\x01\n" +
	"\x13PostNewNoteResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12B\n" +
	"\x0ealarmTimeStamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0ealarmTimeStamp\"\xe7\x01\n" +
	"\x0fPutTaskResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12@\n" +
	"\rinitTimeStamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rinitTimeStamp\x124\n" +
	"\adueDate\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\adueDate\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"\x9b\x01\n" +
	"\x0fPutNoteResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12B\n" +
	"\x0ealarmTimeStamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0ealarmTimeStamp\"\xea\x01\n" +
	"\x12DeleteTaskResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12@\n" +
	"\rinitTimeStamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rinitTimeStamp\x124\n" +
	"\adueDate\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\adueDate\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"\x9e\x01\n" +
	"\x12DeleteNoteResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12B\n" +
	"\x0ealarmTimeStamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0ealarmTimeStamp2\xc6\x06\n" +
	"\x12RemindablesService\x12E\n" +
	"\bGetTasks\x12\x16.google.protobuf.Empty\x1a\x1f.remindables.v1.GetTaskResponse0\x01\x12E\n" +
	"\bGetNotes\x12\x16.google.protobuf.Empty\x1a\x1f.remindables.v1.GetNoteResponse0\x01\x12O\n" +
	"\fGetTasksById\x12\x1e.remindables.v1.GetTaskRequest\x1a\x1f.remindables.v1.GetTaskResponse\x12O\n" +
	"\fGetNotesById\x12\x1e.remindables.v1.GetNoteRequest\x1a\x1f.remindables.v1.GetNoteResponse\x12V\n" +
	"\vPostNewTask\x12\".remindables.v1.PostNewTaskRequest\x1a#.remindables.v1.PostNewTaskResponse\x12V\n" +
	"\vPostNewNote\x12\".remindables.v1.PostNewNoteRequest\x1a#.remindables.v1.PostNewNoteResponse\x12N\n" +
	"\vPutTaskById\x12\x1e.remindables.v1.PutTaskRequest\x1a\x1f.remindables.v1.PutTaskResponse\x12N\n" +
	"\vPutNoteById\x12\x1e.remindables.v1.PutNoteRequest\x1a\x1f.remindables.v1.PutNoteResponse\x12W\n" +
	"\x0eDeleteTaskById\x12!.remindables.v1.DeleteTaskRequest\x1a\".remindables.v1.DeleteTaskResponse\x12W\n" +
	"\x0eDeleteNoteById\x12!.remindables.v1.DeleteNoteRequest\x1a\".remindables.v1.DeleteNoteResponseB\x1dZ\x1bpkg/grpc/v1/remindables_apib\x06proto3"

var (
	file_api_grpc_v1_remindables_proto_rawDescOnce sync.Once
	file_api_grpc_v1_remindables_proto_rawDescData []byte
)

func file_api_grpc_v1_remindables_proto_rawDescGZIP() []byte {
	file_api_grpc_v1_remindables_proto_rawDescOnce.Do(func() {
		file_api_grpc_v1_remindables_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_grpc_v1_remindables_proto_rawDesc), len(file_api_grpc_v1_remindables_proto_rawDesc)))
	})
	return file_api_grpc_v1_remindables_proto_rawDescData
}

var file_api_grpc_v1_remindables_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_grpc_v1_remindables_proto_goTypes = []any{
	(*GetTaskRequest)(nil),        // 0: remindables.v1.GetTaskRequest
	(*GetNoteRequest)(nil),        // 1: remindables.v1.GetNoteRequest
	(*PostNewTaskRequest)(nil),    // 2: remindables.v1.PostNewTaskRequest
	(*PostNewNoteRequest)(nil),    // 3: remindables.v1.PostNewNoteRequest
	(*PutTaskRequest)(nil),        // 4: remindables.v1.PutTaskRequest
	(*PutNoteRequest)(nil),        // 5: remindables.v1.PutNoteRequest
	(*DeleteTaskRequest)(nil),     // 6: remindables.v1.DeleteTaskRequest
	(*DeleteNoteRequest)(nil),     // 7: remindables.v1.DeleteNoteRequest
	(*GetTaskResponse)(nil),       // 8: remindables.v1.GetTaskResponse
	(*GetNoteResponse)(nil),       // 9: remindables.v1.GetNoteResponse
	(*PostNewTaskResponse)(nil),   // 10: remindables.v1.PostNewTaskResponse
	(*PostNewNoteResponse)(nil),   // 11: remindables.v1.PostNewNoteResponse
	(*PutTaskResponse)(nil),       // 12: remindables.v1.PutTaskResponse
	(*PutNoteResponse)(nil),       // 13: remindables.v1.PutNoteResponse
	(*DeleteTaskResponse)(nil),    // 14: remindables.v1.DeleteTaskResponse
	(*DeleteNoteResponse)(nil),    // 15: remindables.v1.DeleteNoteResponse
	(*timestamppb.Timestamp)(nil), // 16: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 17: google.protobuf.Empty
}
var file_api_grpc_v1_remindables_proto_depIdxs = []int32{
	16, // 0: remindables.v1.PostNewTaskRequest.dueDate:type_name -> google.protobuf.Timestamp
	16, // 1: remindables.v1.PostNewNoteRequest.alarmTimeStamp:type_name -> google.protobuf.Timestamp
	16, // 2: remindables.v1.PutTaskRequest.dueDate:type_name -> google.protobuf.Timestamp
	16, // 3: remindables.v1.PutNoteRequest.alarmTimeStamp:type_name -> google.protobuf.Timestamp
	16, // 4: remindables.v1.GetTaskResponse.initTimeStamp:type_name -> google.protobuf.Timestamp
	16, // 5: remindables.v1.GetTaskResponse.dueDate:type_name -> google.protobuf.Timestamp
	16, // 6: remindables.v1.GetNoteResponse.alarmTimeStamp:type_name -> google.protobuf.Timestamp
	16, // 7: remindables.v1.PostNewTaskResponse.initTimeStamp:type_name -> google.protobuf.Timestamp
	16, // 8: remindables.v1.PostNewTaskResponse.dueDate:type_name -> google.protobuf.Timestamp
	16, // 9: remindables.v1.PostNewNoteResponse.alarmTimeStamp:type_name -> google.protobuf.Timestamp
	16, // 10: remindables.v1.PutTaskResponse.initTimeStamp:type_name -> google.protobuf.Timestamp
	16, // 11: remindables.v1.PutTaskResponse.dueDate:type_name -> google.protobuf.Timestamp
	16, // 12: remindables.v1.PutNoteResponse.alarmTimeStamp:type_name -> google.protobuf.Timestamp
	16, // 13: remindables.v1.DeleteTaskResponse.initTimeStamp:type_name -> google.protobuf.Timestamp
	16, // 14: remindables.v1.DeleteTaskResponse.dueDate:type_name -> google.protobuf.Timestamp
	16, // 15: remindables.v1.DeleteNoteResponse.alarmTimeStamp:type_name -> google.protobuf.Timestamp
	17, // 16: remindables.v1.RemindablesService.GetTasks:input_type -> google.protobuf.Empty
	17, // 17: remindables.v1.RemindablesService.GetNotes:input_type -> google.protobuf.Empty
	0,  // 18: remindables.v1.RemindablesService.GetTasksById:input_type -> remindables.v1.GetTaskRequest
	1,  // 19: remindables.v1.RemindablesService.GetNotesById:input_type -> remindables.v1.GetNoteRequest
	2,  // 20: remindables.v1.RemindablesService.PostNewTask:input_type -> remindables.v1.PostNewTaskRequest
	3,  // 21: remindables.v1.RemindablesService.PostNewNote:input_type -> remindables.v1.PostNewNoteRequest
	4,  // 22: remindables.v1.RemindablesService.PutTaskById:input_type -> remindables.v1.PutTaskRequest
	5,  // 23: remindables.v1.RemindablesService.PutNoteById:input_type -> remindables.v1.PutNoteRequest
	6,  // 24: remindables.v1.RemindablesService.DeleteTaskById:input_type -> remindables.v1.DeleteTaskRequest
	7,  // 25: remindables.v1.RemindablesService.DeleteNoteById:input_type -> remindables.v1.DeleteNoteRequest
	8,  // 26: remindables.v1.RemindablesService.GetTasks:output_type -> remindables.v1.GetTaskResponse
	9,  // 27: remindables.v1.RemindablesService.GetNotes:output_type -> remindables.v1.GetNoteResponse
	8,  // 28: remindables.v1.RemindablesService.GetTasksById:output_type -> remindables.v1.GetTaskResponse
	9,  // 29: remindables.v1.RemindablesService.GetNotesById:output_type -> remindables.v1.GetNoteResponse
	10, // 30: remindables.v1.RemindablesService.PostNewTask:output_type -> remindables.v1.PostNewTaskResponse
	11, // 31: remindables.v1.RemindablesService.PostNewNote:output_type -> remindables.v1.PostNewNoteResponse
	12, // 32: remindables.v1.RemindablesService.PutTaskById:output_type -> remindables.v1.PutTaskResponse
	13, // 33: remindables.v1.RemindablesService.PutNoteById:output_type -> remindables.v1.PutNoteResponse
	14, // 34: remindables.v1.RemindablesService.DeleteTaskById:output_type -> remindables.v1.DeleteTaskResponse
	15, // 35: remindables.v1.RemindablesService.DeleteNoteById:output_type -> remindables.v1.DeleteNoteResponse
	26, // [26:36] is the sub-list for method output_type
	16, // [16:26] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_api_grpc_v1_remindables_proto_init() }
func file_api_grpc_v1_remindables_proto_init() {
	if File_api_grpc_v1_remindables_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_grpc_v1_remindables_proto_rawDesc), len(file_api_grpc_v1_remindables_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_grpc_v1_remindables_proto_goTypes,
		DependencyIndexes: file_api_grpc_v1_remindables_proto_depIdxs,
		MessageInfos:      file_api_grpc_v1_remindables_proto_msgTypes,
	}.Build()
	File_api_grpc_v1_remindables_proto = out.File
	file_api_grpc_v1_remindables_proto_goTypes = nil
	file_api_grpc_v1_remindables_proto_depIdxs = nil
}
